project:
  type: website
  output-dir: docs

website:
  title: "Dr. Li Ming's Academic Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: 
      - styles.css
    toc: true
    toc-location: right
